config/routes.rb
Recruitment::Application.routes.draw do

  devise_for :users

  root :to => "recruits#new"

  resources :languages

  resources :recruits

end

app/models/knowledge.rb
class Knowledge < ActiveRecord::Base
  belongs_to :recruit
  belongs_to :language
end

app/models/language.rb
class Language < ActiveRecord::Base
  attr_accessible :name
  has_many :knowledge
  has_many :recruits, through: :knowledge
  validates :name, presence: true, length: { maximum: 50 }, 
  			uniqueness: true
end

app/models/recruit.rb
class Recruit < ActiveRecord::Base
  attr_accessible :cellphone, :email, :name, :rails, :residence, :language_ids, :contacted, :promising, :rejected, :comments
  has_many :knowledge
  has_many :languages, through: :knowledge
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  	uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

  before_filter :verify_is_admin, :only => [ :index , :show, :new, :create, :edit, :update, :destroy]

  # GET /languages
  # GET /languages.json
  def index
    @languages = Language.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @languages }
    end
  end

  # GET /languages/1
  # GET /languages/1.json
  def show
    @language = Language.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @language }
    end
  end

  # GET /languages/new
  # GET /languages/new.json
  def new
    @language = Language.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @language }
    end
  end

  # GET /languages/1/edit
  def edit
    @language = Language.find(params[:id])
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(params[:language])

    respond_to do |format|
      if @language.save
        format.html { redirect_to @language, notice: 'Language was successfully created.' }
        format.json { render json: @language, status: :created, location: @language }
      else
        format.html { render action: "new" }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /languages/1
  # PUT /languages/1.json
  def update
    @language = Language.find(params[:id])

    respond_to do |format|
      if @language.update_attributes(params[:language])
        format.html { redirect_to @language, notice: 'Language was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language = Language.find(params[:id])
    @language.destroy

    respond_to do |format|
      format.html { redirect_to languages_url }
      format.json { head :no_content }
    end
  end

  def verify_is_admin
    (current_user.nil?) ? redirect_to(new_user_session_path) : (redirect_to(recruits_path) unless current_user.admin?)
  end
end

app/controllers/recruits_controller.rb
class RecruitsController < ApplicationController

  # before_filter :verify_is_admin, :only => [ :index , :update, :destroy]
  before_filter :authenticate_user!

  # GET /recruits
  # GET /recruits.json
  def index
    @recruits = Recruit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @recruits }
    end
  end

  # GET /recruits/1
  # GET /recruits/1.json
  def show
    @recruit = Recruit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @recruit }
    end
  end

  # GET /recruits/new
  # GET /recruits/new.json
  def new
    @recruit = Recruit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @recruit }
    end
  end

  # GET /recruits/1/edit
  def edit
    @recruit = Recruit.find(params[:id])
  end

  # POST /recruits
  # POST /recruits.json
  def create
    @recruit = Recruit.new(params[:recruit])

    respond_to do |format|
      if @recruit.save
        format.html { redirect_to @recruit, notice: 'Recruit was successfully created.' }
        format.json { render json: @recruit, status: :created, location: @recruit }
      else
        format.html { render action: "new" }
        format.json { render json: @recruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /recruits/1
  # PUT /recruits/1.json
  def update
    @recruit = Recruit.find(params[:id])

    respond_to do |format|
      if @recruit.update_attributes(params[:recruit])
        format.html { redirect_to @recruit, notice: 'Recruit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @recruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recruits/1
  # DELETE /recruits/1.json
  def destroy
    @recruit = Recruit.find(params[:id])
    @recruit.destroy

    respond_to do |format|
      format.html { redirect_to recruits_url }
      format.json { head :no_content }
    end
  end

  private

  # def verify_is_admin
  #   (current_user.nil?) ? redirect_to(new_user_session_path) : (redirect_to(recruits_path) unless current_user.admin?)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def language(i)
		if @recruit
			@recruit.languages.include?(i)
		else
			false
		end
	end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/recruits_helper.rb
module RecruitsHelper
end

app/views/languages/_form.html.erb
<%= form_for(@language) do |f| %>
  <% if @language.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@language.errors.count, "error") %> prohibited this language from being saved:</h2>

      <ul>
      <% @language.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/languages/edit.html.erb
<h1>Editing language</h1>

<%= render 'form' %>

<%= link_to 'Show', @language %> |
<%= link_to 'Back', languages_path %>

app/views/languages/index.html.erb
<h1>Listing languages</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @languages.each do |language| %>
  <tr>
    <td><%= language.name %></td>
    <td><%= link_to 'Show', language %></td>
    <td><%= link_to 'Edit', edit_language_path(language) %></td>
    <td><%= link_to 'Destroy', language, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Language', new_language_path %>

app/views/languages/new.html.erb
<h1>New language</h1>

<%= render 'form' %>

<%= link_to 'Back', languages_path %>

app/views/languages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @language.name %>
</p>


<%= link_to 'Edit', edit_language_path(@language) %> |
<%= link_to 'Back', languages_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recruitment</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="container">

		<div id="user_nav">
			<% if user_signed_in? %>
				Signed in as <%= current_user.email %>. Not you?
				<%= link_to "Sign_out", destroy_user_session_path, data: { method: "delete" } %>
			<% end %>
		</div>

		<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

		<%= yield %>
	</div>
</body>
</html>

app/views/recruits/_form.html.erb
<%= form_for(@recruit) do |f| %>
  <% if @recruit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recruit.errors.count, "error") %> prohibited this recruit from being saved:</h2>

      <ul>
      <% @recruit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :cellphone %><br />
    <%= f.text_field :cellphone %>
  </div>
  <div class="field">
    <%= f.label :residence %><br />
    <%= f.text_field :residence %>
  </div>
  <div class="field">
    <%= f.check_box :rails %> <%= f.label :rails %>
  </div>
  <div class="field">
    <%= hidden_field_tag "recruit[language_ids[]", nil %>
    <% Language.all.each do |lang| -%>
      <%= check_box_tag "recruit[language_ids[]", lang.id, 
        @recruit.language_ids.include?(lang.id), id: dom_id(lang) %>
      <%= label_tag dom_id(lang), lang.name %>
    <% end -%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/recruits/edit.html.erb
<h1>Editing recruit</h1>

<%= render 'form' %>

<div class="field">

</div>

<%= link_to 'Show', @recruit %> 
<% if user_signed_in? %>
| <%= link_to 'Back', recruits_path %>
<% end %>

app/views/recruits/index.html.erb
<h1>Listing recruits</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Cellphone</th>
    <th>Residence</th>
    <th>Rails</th>
    <th>Technologies</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @recruits.each do |recruit| %>
  <tr>
    <td><%= recruit.name %></td>
    <td><%= recruit.email %></td>
    <td><%= recruit.cellphone %></td>
    <td><%= recruit.residence %></td>
    <td><%= recruit.rails %></td>
    <td><% recruit.languages.each do |language| %>
            <%= "#{language.name}, " %>
        <% end %>
    </td>
    <td><%= link_to 'Show', recruit %></td>
    <td><%= link_to 'Edit', edit_recruit_path(recruit) %></td>
    <td><%= link_to 'Destroy', recruit, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Recruit', new_recruit_path %>

app/views/recruits/new.html.erb
<h1>New recruit</h1>

<%= render 'form' %>
<!--
<%= link_to 'Back', recruits_path %>
-->

app/views/recruits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @recruit.name %>
</p>

<p>
  <b>Email:</b>
  <%= @recruit.email %>
</p>

<p>
  <b>Cellphone:</b>
  <%= @recruit.cellphone %>
</p>

<p>
  <b>Residence:</b>
  <%= @recruit.residence %>
</p>

<p>
  <b>Rails:</b>
  <%= @recruit.rails %>
</p>

<p>
  <b>Technologies</b>
  <ul>
    <% @recruit.languages.each do |language| %>
      <li><%= language.name %></li>
    <% end %>
  </ul>
</p>


<%= link_to 'Edit', edit_recruit_path(@recruit) %> |

<% if user_signed_in? %>
  <%= link_to 'Back', recruits_path %>
<% else %>
  <%= link_to 'Finish', new_recruit_path %>
<% end %>